### ISSUE TITLE
No module named elementtree

### ISSUE THREAD

**Issue by patrickwelker** [grych/AppStoreReviews#6]
I'm running the default Python 2.7.6 on OS X 10.10 and have installed the two modules as advised. I still get:

```
$ AppStoreReviews.py -help
>>> Traceback (most recent call last):
>>>   File "/Users/me/Dropbox/bin/AppStoreReviews.py", line 13, in <module>
from elementtree import ElementTree
>>> ImportError: No module named elementtree
```

Any tips on how to get this running? I'm a Python novice, just wanting to get your script starting.

**Comment by grych** [comment]
You need an “elementtree” module installed: easy_install elementtree

> On 05 Nov 2014, at 07:59, Patrick Welker notifications@github.com wrote:
> 
> I'm running the default Python 2.7.6 on OS X 10.10 and have installed the two modules as advised. I still get:
> 
> $ AppStoreReviews.py -help
> 
> > > > Traceback (most recent call last):
> > > >   File "/Users/me/Dropbox/bin/AppStoreReviews.py", line 13, in <module>
> > > > from elementtree import ElementTree
> > > > ImportError: No module named elementtree
> > > > Any tips on how to get this running? I'm a Python novice, just wanting to get your script starting.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/grych/AppStoreReviews/issues/6.

## 

Grych

**Comment by ghost** [comment]
`from elementtree import ElementTree`

to

`from xml.etree import ElementTree`
